// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelCabinet.Server.Data;

#nullable disable

namespace ModelCabinet.Server.Migrations
{
    [DbContext(typeof(ModelCabinetContext))]
    [Migration("20250203233313_AddedTagging")]
    partial class AddedTagging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetTag", b =>
                {
                    b.Property<int>("AssetTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("TaggedAssetsAssetId")
                        .HasColumnType("int");

                    b.HasKey("AssetTagsTagID", "TaggedAssetsAssetId");

                    b.HasIndex("TaggedAssetsAssetId");

                    b.ToTable("AssetTag");
                });

            modelBuilder.Entity("ModelCabinet.Server.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            DateCreation = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8202),
                            DateUpdated = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8204),
                            FileSize = 446684L,
                            Name = "Test Asset",
                            Path = "C:\\Projects\\Visual_Studio\\ASP-NET\\ModelCabinet-Fork\\ModelCabinet.Server\\bin\\Debug\\net8.0\\Assets\\TestProject\\HelloWorld.stl",
                            ProjectId = 1
                        },
                        new
                        {
                            AssetId = 2,
                            DateCreation = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8209),
                            DateUpdated = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8210),
                            FileSize = 11285384L,
                            Name = "Benchy",
                            Path = "C:\\Projects\\Visual_Studio\\ASP-NET\\ModelCabinet-Fork\\ModelCabinet.Server\\bin\\Debug\\net8.0\\Assets\\TestProject\\3DBenchy.stl",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("ModelCabinet.Server.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Author = "Author",
                            CreationDate = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(7995),
                            Description = "Description",
                            ModifiedDate = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8047),
                            Name = "Test Project",
                            ShortDescription = "Desc",
                            Slug = "nomen est omen",
                            Version = "0.0.1"
                        },
                        new
                        {
                            ProjectId = 2,
                            Author = "Author",
                            CreationDate = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8051),
                            Description = "Description",
                            ModifiedDate = new DateTime(2025, 2, 3, 15, 33, 13, 315, DateTimeKind.Local).AddTicks(8052),
                            Name = "Test Project Two",
                            ShortDescription = "Desc",
                            Slug = "nomen est omen",
                            Version = "0.0.1"
                        });
                });

            modelBuilder.Entity("ModelCabinet.Server.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TagID");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            TagName = "Testing"
                        },
                        new
                        {
                            TagID = 2,
                            TagName = "In Development"
                        },
                        new
                        {
                            TagID = 3,
                            TagName = "Ready To Print"
                        },
                        new
                        {
                            TagID = 4,
                            TagName = "Modular"
                        });
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.Property<int>("ProjectTagsTagID")
                        .HasColumnType("int");

                    b.Property<int>("TaggedProjectsProjectId")
                        .HasColumnType("int");

                    b.HasKey("ProjectTagsTagID", "TaggedProjectsProjectId");

                    b.HasIndex("TaggedProjectsProjectId");

                    b.ToTable("ProjectTag");
                });

            modelBuilder.Entity("AssetTag", b =>
                {
                    b.HasOne("ModelCabinet.Server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("AssetTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelCabinet.Server.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("TaggedAssetsAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelCabinet.Server.Models.Asset", b =>
                {
                    b.HasOne("ModelCabinet.Server.Models.Project", null)
                        .WithMany("Assets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.HasOne("ModelCabinet.Server.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("ProjectTagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelCabinet.Server.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("TaggedProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelCabinet.Server.Models.Project", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
